const fs = require('fs');
const path = require('path');
const https = require('https');

const ROOT_DIR = path.resolve(__dirname, '..');
const DOCS_DIR = path.join(ROOT_DIR, 'docs');

async function generateAISummary(analysisStr) {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
        console.warn('OPENAI_API_KEY not found. Using fallback dynamic summary.');
        return '*(AI summary generation skipped - No API key provided. Add OPENAI_API_KEY to your repository secrets to enable AI documentation.)*';
    }

    return new Promise((resolve) => {
        const payload = JSON.stringify({
            model: "gpt-3.5-turbo",
            messages: [
                {
                    role: "system",
                    content: "You are an expert technical writer. Write a succinct architecture summary (2-3 paragraphs) based on the repository analysis."
                },
                {
                    role: "user",
                    content: `Analyze this repository data and provide a summary:\n\n${analysisStr}`
                }
            ],
            max_tokens: 300
        });

        const req = https.request({
            hostname: 'api.openai.com',
            port: 443,
            path: '/v1/chat/completions',
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${apiKey}`,
                'Content-Length': payload.length
            }
        }, res => {
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                try {
                    const response = JSON.parse(data);
                    if (response.choices && response.choices.length > 0) {
                        resolve(response.choices[0].message.content);
                    } else {
                        resolve('*(AI generation failed: Invalid response from API)*');
                    }
                } catch {
                    // ignore error
                    resolve('*(AI generation failed: Could not parse response)*');
                }
            });
        });

        req.on('error', err => resolve(`*(AI generation error: ${err.message})*`));
        req.write(payload);
        req.end();
    });
}

async function updateReadme(analysis) {
    const readmePath = path.join(ROOT_DIR, 'README.md');
    let currentReadme = '';

    if (fs.existsSync(readmePath)) {
        currentReadme = fs.readFileSync(readmePath, 'utf-8');
    }

    let archDiagram = '';
    try {
        archDiagram = fs.readFileSync(path.join(DOCS_DIR, 'architecture.md'), 'utf-8');
    } catch {
        // ignore error
        console.warn('Could not load diagrams for README.');
    }

    const techStack = analysis.technologies.map(t => `- ${t}`).join('\n');

    console.log('Requesting AI summary...');
    const aiSummary = await generateAISummary(JSON.stringify(analysis));

    const markerStart = '<!-- AUTO-GENERATED-DOCS:START -->';
    const markerEnd = '<!-- AUTO-GENERATED-DOCS:END -->';

    const autoGeneratedContent = `
${markerStart}
## 🤖 Autonomous Repository Analysis

*Last Updated: ${new Date().toISOString()}*

### 🧠 AI Architecture Summary
${aiSummary}

### 📊 Repository Structure
\`\`\`text
${analysis.structure}
\`\`\`

### 🛠️ Detected Technologies
${techStack}

### 🏗️ Dynamic Architecture Diagram

${archDiagram}

${markerEnd}
`;

    if (currentReadme.includes(markerStart)) {
        const regex = new RegExp(`${markerStart}[\\s\\S]*?${markerEnd}`);
        currentReadme = currentReadme.replace(regex, autoGeneratedContent.trim());
    } else {
        currentReadme += `\n\n${autoGeneratedContent}`;
    }

    fs.writeFileSync(readmePath, currentReadme);
    console.log('README.md updated automatically.');
}

async function updateDocs() {
    console.log('AI Documentation Agent: Updating docs...');

    const analysisPath = path.join(ROOT_DIR, 'scripts', 'analysis.json');
    if (!fs.existsSync(analysisPath)) {
        console.error('analysis.json not found!');
        process.exit(1);
    }

    const analysis = JSON.parse(fs.readFileSync(analysisPath, 'utf-8'));
    await updateReadme(analysis);
}

updateDocs();
